
email-smtp-svr-addr: 127.0.0.1:1025
email-smtp-username: admin
email-smtp-password: admin
email-addr-from: noreply@cycloid.io
email-addr-return-path: "admin+ydbounce@cycloid.io"
email-tls-skip-verify: true
email-addr-to: test@email.com
